config/routes.rb
Rails.application.routes.draw do
  get 'nearby/index'

  get 'messaging' => 'messaging#send_message'

  root to:'nearby#index'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/messaging_controller.rb
class MessagingController < ApplicationController
  include ActionController::Live
  require 'tweetstream'

  def send_message
    response.headers['Content-Type'] = 'text/event-stream'

    client = TweetStream::Client.new

    if params[:lat]
      start = Geokit::LatLng.new(params[:lat].to_f, params[:lng].to_f)
    else
      start = Geokit::LatLng.new(40.713938, -73.9790146)
    end

    box_size = 1
    box = [start.lng - box_size, start.lat - box_size, start.lng + box_size, start.lat + box_size]

    puts "Starting stream for #{box}"

    EM.run do

      client.on_error do |error|
        puts "TweetStreem Error: #{error}"
      end

      client.locations(box) do |object|
        begin
          if object.is_a?(Twitter::Tweet)
            store_tweet(object)
            score = tweet_score(object)
            location = Geokit::LatLng.new(object.geo.lat, object.geo.long)
            distance = start.distance_to(location).round(1)

            word_scores = words_with_scores(object)
            scores = word_scores.inject({}) { |acc, val| acc[val[:score].to_i] = val[:word]; acc }
            max_word = scores[scores.keys.max]

            object_data = {
              text: "#{score} (#{max_word}) : #{distance} : #{object.text}",
              distance: distance,
              score: tweet_score(object),
              word_scores: word_scores,
            }

            puts object_data.inspect
            response.stream.write "data: #{object_data.to_json}\nretry: 10000\n\n"
          else
            response.stream.write "data: #{object.inspect.to_json}\nretry: 10000\n\n"
          end
        rescue => error
          puts "Error in stream: #{error.message}: #{error.backtrace}"
          response.stream.close
        end
      end

    end

  rescue => error
    binding.pry
  ensure
    begin
      client.stop if client
    rescue
    end
    response.stream.close
  end

  def redis
    @redis ||= Redis.new
  end

  def store_tweet(tweet)
    redis.pipelined do
      tweet.text.split(' ').each do |word|
        key = "word:#{word}"
        redis.incr(key)
        redis.expire(key, 300)
      end
    end
  end

  def tweet_words(tweet)
    tweet.text.split(' ')
  end

  def words_with_scores(tweet)
    scores = word_scores(tweet)
    tweet_words(tweet).reject{|word| word.length < 4}.each_with_index.map{ |word, index| {word: word, score: scores[index] }}
  end

  def word_scores(tweet)
    redis.pipelined do
      tweet_words(tweet).reject{|word| word.length < 4}.each do |word|
        redis.get("word:#{word}")
      end
    end
  end

  def tweet_score(tweet)
    word_scores(tweet).max
  end
end

app/controllers/nearby_controller.rb
class NearbyController < ApplicationController
  def index
=begin
    client = Twitter::REST::Client.new do |config|
      config.consumer_key    = "wU8W1AIcKGaPWFxRbrnbUkiA4"
      config.consumer_secret = "IbqCk0VOjgo8G1SOiTt25U6B470986N4rGRHitSjg97ASMdz6v"
    end

    stream = Twitter::Streaming::Client.new do |config|
      config.consumer_secret = "IbqCk0VOjgo8G1SOiTt25U6B470986N4rGRHitSjg97ASMdz6v"
      config.consumer_key    = "wU8W1AIcKGaPWFxRbrnbUkiA4"
      config.access_token = "16500296-CMk2BzxkYBzLl7aXTyfzG9lc6usc6d8pdO0xzfysC"
      config.access_token_secret = "ay4av6fQN1kZ3oEJ7OqCzfBDTnliGrs4X8VSoZpkFrwkr"
    end

    location = params[:location]
    query = "geocode:#{location},1mi"
    tweets = client.search(query, :result_type => "recent")
    @results = Array.new
    tweets.each do |tweet|
      if !@results.any?{|t| t.text == tweet.text}
        @results << tweet
      end
      if @results.count > 20
        break
      end
    end
=end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messaging_helper.rb
module MessagingHelper
end

app/helpers/nearby_helper.rb
module NearbyHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rightherenow</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/nearby/index.html.slim
h1 Nearby

= form_tag nearby_index_path, method: :get
= label_tag 'location'
= text_field_tag 'location', '40.713938,-73.9790146'
= submit_tag 'go'

div.nearby
  div#card-holder

javascript:
  var geo = $('#location')[0];
  var url = '/messaging';

  if (geo) {
    var lat = geo.value.split(',')[0];
    var lng = geo.value.split(',')[1];
    url += '?lat=' + lat + '&lng=' + lng;
  }

  var source = new EventSource(url);

  source.addEventListener('message', function(e) {
    var data = JSON.parse(e.data);

    var card = document.createElement('div');
    card.className = 'card';
    card.style.backgroundColor = 'rgb(255,255,' + (255 - data.score) + ')';

    if (data.score) {
      card.setAttribute('data-score', data.score);
      card.setAttribute('data-distance', Math.round(data.distance));
    }

    var node = document.createTextNode(data.text);
    card.appendChild(node);

    var cardHolder = document.getElementById('card-holder');
    if (cardHolder && cardHolder.hasChildNodes()) {
      var firstElement = cardHolder.childNodes[0];
    }
    cardHolder.insertBefore(card, firstElement);
    $('.card').tsort('',{data:'distance', order:'asc'});
  }, false);

  source.addEventListener('open', function(e) {
    // Connection was opened.
  }, false);

  source.addEventListener('error', function(e) {
    if (e.readyState == EventSource.CLOSED) {
    // Connection was closed.
    }
   }, false);